spring:
  application:
    name: SpringRedis

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect